Repository RobertBeaudenon/SOEN390-CampusGuideMap, pull requests merged in 2020-03, with the labels that each got.

#49 Issue #5 - Building Highlighting (adding tests)
  app/build.gradle
  app/src/main/java/com/droidhats/campuscompass/viewmodels/MapViewModel.kt
  app/src/main/java/com/droidhats/campuscompass/views/MapFragment.kt
  app/src/test/java/com/droidhats/campuscompass/MapRepositoryTest.kt
  app/src/test/java/com/droidhats/campuscompass/MapViewModelTest.kt
Labels: Testing

#50 Issue #12 - Calendar Event navigation button, refactoring, and View Model Test
  app/src/main/java/com/droidhats/campuscompass/viewmodels/CalendarViewModel.kt
  app/src/main/java/com/droidhats/campuscompass/views/CalendarFragment.kt
  app/src/main/java/com/droidhats/campuscompass/views/MapFragment.kt
  app/src/main/res/drawable/ic_directions_60dp.xml
  app/src/main/res/layout/calendar_recycler_item.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/com/droidhats/campuscompass/CalendarViewModelTest.kt
Labels: Refactor, Testing

#54 Issue #12 - Calendar
  app/build.gradle
  app/src/androidTest/java/com/droidhats/campuscompass/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/droidhats/campuscompass/views/CalendarFragmentTest.kt
  app/src/main/java/com/droidhats/campuscompass/models/Calendar.kt
  app/src/main/java/com/droidhats/campuscompass/models/CalendarEvent.kt
  app/src/main/java/com/droidhats/campuscompass/models/Map.kt
  app/src/main/java/com/droidhats/campuscompass/repositories/CalendarRepository.kt
  app/src/test/java/com/droidhats/campuscompass/ExampleUnitTest.kt
  app/src/test/java/com/droidhats/campuscompass/models/CalendarEventTest.kt
  app/src/test/java/com/droidhats/campuscompass/models/CalendarTest.kt
  app/src/test/java/com/droidhats/campuscompass/repositories/CalendarRepositoryTest.kt
  app/src/test/java/com/droidhats/campuscompass/repositories/MapRepositoryTest.kt
  app/src/test/java/com/droidhats/campuscompass/viewmodels/CalendarViewModelTest.kt
  app/src/test/java/com/droidhats/campuscompass/viewmodels/MapViewModelTest.kt
  app/src/test/java/com/droidhats/campuscompass/viewmodels/RxImmediateSchedulerRule.kt
  app/src/test/java/com/droidhats/campuscompass/viewmodels/SplashViewModelTest.kt
  build.gradle
Labels: Testing

#58 Issue #9: Transit transportation mode + Step by step Instructions revamp
  app/build.gradle
  app/src/main/assets/buildings.json
  app/src/main/java/com/droidhats/campuscompass/views/InstructionsFragment.kt
  app/src/main/java/com/droidhats/campuscompass/views/MapFragment.kt
  app/src/main/res/layout/bottom_sheet_layout.xml
  app/src/main/res/layout/map_fragment.xml
  build.gradle
Labels: enhancement

#64 Issue #2: Refactored the MapFragment, MapViewModel and MapRepository to better represent the MVVM structure
  app/build.gradle
  app/src/main/java/com/droidhats/campuscompass/models/Map.kt
  app/src/main/java/com/droidhats/campuscompass/repositories/MapRepository.kt
  app/src/main/java/com/droidhats/campuscompass/viewmodels/MapViewModel.kt
  app/src/main/java/com/droidhats/campuscompass/views/MapFragment.kt
  app/src/test/java/com/droidhats/campuscompass/repositories/MapRepositoryTest.kt
Labels: Refactor

#66 issue #65 side menu to access app features
  app/build.gradle
  app/src/androidTest/java/com/droidhats/campuscompass/views/MapFragmentTest.kt
  app/src/androidTest/java/com/droidhats/campuscompass/views/NavigationDrawerTest.kt
  app/src/main/res/drawable/ic_title_dark.png
  app/src/main/res/drawable/icon_explore.png
  app/src/main/res/drawable/icon_heart.png
  app/src/main/res/drawable/icon_ressources.png
  app/src/main/res/drawable/icon_schedule.png
  app/src/main/res/drawable/icon_settings.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/layout/nav_drawer_header_main_layout.xml
  app/src/main/res/menu/nav_drawer_main_menu.xml
  build.gradle
Labels: Testing

#69 Issues #2, #7, #12, #16, #23 Combined Unit and UI Test Coverage using JaCoCo
  app/build.gradle
  app/src/androidTest/java/com/droidhats/campuscompass/views/CalendarFragmentTest.kt
  app/src/androidTest/java/com/droidhats/campuscompass/views/MapFragmentTest.kt
  app/src/androidTest/java/com/droidhats/campuscompass/views/NavigationDrawerTest.kt
  app/src/androidTest/java/com/droidhats/campuscompass/views/SplashFragmentTest.kt
  app/src/main/java/com/droidhats/campuscompass/views/SplashFragment.kt
  app/src/test/java/com/droidhats/campuscompass/repositories/MapRepositoryTest.kt
  app/src/test/java/com/droidhats/campuscompass/viewmodels/RxImmediateSchedulerRule.kt
  app/src/test/java/com/droidhats/campuscompass/viewmodels/SplashViewModelTest.kt
  build.gradle
Labels: Testing

#72 Issues #8, #9, #10, #32 - UI tests for search bar, place info card and methods of transportation
  app/src/androidTest/java/com/droidhats/campuscompass/views/MapFragmentTest.kt
  app/src/main/res/layout/search_fragment.xml
Labels: Testing

#76 Issue #26 Outdoor directions steps & Epic #7 enhancement
  app/src/androidTest/java/com/droidhats/campuscompass/views/DirectionsTest.kt
  app/src/main/java/com/droidhats/campuscompass/adapters/SearchAdapter.kt
  app/src/main/java/com/droidhats/campuscompass/repositories/NavigationRepository.kt
  app/src/main/java/com/droidhats/campuscompass/views/InstructionsFragment.kt
  app/src/main/java/com/droidhats/campuscompass/views/MapFragment.kt
  app/src/main/java/com/droidhats/campuscompass/views/SearchFragment.kt
  app/src/main/res/layout/instructions_sheet_layout.xml
  app/src/main/res/layout/map_fragment.xml
  app/src/main/res/layout/search_bar_layout.xml
  app/src/main/res/mipmap/ic_buildings/drawable/arrow_button.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#74 #65 - navigation from side menu to map fragment
  .gitignore
  app/src/androidTest/java/com/droidhats/campuscompass/views/DirectionsTest.kt
  app/src/androidTest/java/com/droidhats/campuscompass/views/MapFragmentTest.kt
  app/src/androidTest/java/com/droidhats/campuscompass/views/NavigationDrawerTest.kt
  app/src/main/java/com/droidhats/campuscompass/MainActivity.kt
  app/src/main/java/com/droidhats/campuscompass/models/Map.kt
  app/src/main/java/com/droidhats/campuscompass/viewmodels/MapViewModel.kt
  app/src/main/java/com/droidhats/campuscompass/views/CalendarFragment.kt
  app/src/main/java/com/droidhats/campuscompass/views/MapFragment.kt
  app/src/main/java/com/droidhats/campuscompass/views/SplashFragment.kt
  app/src/main/res/drawable-nodpi/icon_map.png
  app/src/main/res/drawable-nodpi/icon_menu.png
  app/src/main/res/drawable/baseline_near_me_white_36dp.png
  app/src/main/res/layout/bottom_sheet_layout.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/layout/nav_drawer_header_main_layout.xml
  app/src/main/res/menu/nav_drawer_main_menu.xml
  app/src/main/res/mipmap/ic_buildings/drawable-hdpi/ic_action_name.png
  app/src/main/res/mipmap/ic_buildings/drawable-mdpi/ic_action_name.png
  app/src/main/res/mipmap/ic_buildings/drawable-xhdpi/ic_action_name.png
  app/src/main/res/mipmap/ic_buildings/drawable-xxhdpi/ic_action_name.png
  app/src/main/res/mipmap/ic_buildings/drawable-xxxhdpi/ic_action_name.png
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Testing, enhancement
